# Site settings
title: Ryan and Sarah
email: rg.crichton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are getting married! This is our website where we can keep you
  up-to-date on details, what we are up to and how the planning is going. 
  Stay tuned!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rgcrichton

# Build settings
markdown: kramdown
